server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://univeristy-db.mysql.database.azure.com:3306/university_system?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: uniAppAdmin@univeristy-db
    password:  ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  config: classpath:log4j2.yml

jwt:
  secret: tuSecretKey
  token:
    validity: {TOKEN_VALIDITY}
